In [ ]:
import numpy as np

In [5]:
# Створіть одновимірний масив (вектор) зі значеннями натуральних чисел, починаючи з 1, та виведіть його значення.
n = np.random.randint(1, 10)
arr = np.arange(1, n+1)

print(arr)

[1 2 3 4]


In [6]:
# Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його косинусами кожного натурального числа, починаючи з 1, та виведіть його значення.
arr = np.arange(1, 10).reshape(3, 3)
arr = np.cos(arr)

print(arr)

[[ 0.54030231 -0.41614684 -0.9899925 ]
 [-0.65364362  0.28366219  0.96017029]
 [ 0.75390225 -0.14550003 -0.91113026]]


In [26]:
# Створіть масив розміром 3x3, заповніть його випадковими цілими числами від -5 до 5 та виведіть непарні числа.
arr = np.random.randint(-5, 6, size=(3, 3))
arr = arr[arr % 2 != 0]

print(arr)

[ 1 -5  1  1]


In [27]:
# Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від -0.7 до 0.7 та виведіть його значення
arr = np.random.uniform(-0.7, 0.7, size=(4, 4))
print(arr)

[[-0.19255266  0.48760575  0.63097713  0.61182749]
 [ 0.14594803  0.12837178 -0.23534333  0.0707872 ]
 [ 0.46990793  0.33882385 -0.61102014 -0.62847473]
 [ 0.6007475   0.04486787  0.63040886  0.34977271]]


In [29]:
# Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 10 до 20 та виконайте на них поелементні операції додавання, віднімання та множення.
arr1 = np.random.randint(10, 21, size=5)
arr2 = np.random.randint(10, 21, size=5)

print(arr1 + arr2)
print(arr1 - arr2)
print(arr1 * arr2)

[35 39 30 24 23]
[-5 -1 -4  2  3]
[300 380 221 143 130]


In [30]:
# Створіть дві матриці 4x4, заповніть їх довільними цілими числами від 1 до 10 та знайдіть їх добуток.
arr1 = np.random.randint(1, 11, size=(4, 4))
arr2 = np.random.randint(1, 11, size=(4, 4))

print(np.dot(arr1, arr2))

[[150 130 238 202]
 [169 120 261 237]
 [101  78 145 143]
 [121 112 174 125]]


In [31]:
# Створіть дві матриці розміром 2x3 та 3x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 5 та перемножте їх між собою.
arr1 = np.random.randint(1, 6, size=(2, 3))
arr2 = np.random.randint(1, 6, size=(3, 3))

print(np.dot(arr1, arr2))

[[35 39 24]
 [33 38 22]]


In [32]:
# Створіть матрицю розміром 2x2, заповніть її випадковими цілими числами в діапазоні від 1 до 12 та знайдіть її обернену матрицю.
arr = np.random.randint(1, 13, size=(2, 2))
arr_inv = np.linalg.inv(arr)

print(arr_inv)

[[-0.04098361  0.09016393]
 [ 0.09836066 -0.01639344]]


In [33]:
# Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.
arr = np.random.rand(3, 3)
arr = arr.T

print(arr)

[[0.66194198 0.57019483 0.64048953]
 [0.27556065 0.77200564 0.80782598]
 [0.9886685  0.71759985 0.94290054]]


In [35]:
# Створіть матрицю розміром 3x4 та вектор розміром 4x1, заповніть матрицю випадковими цілими числами в діапазоні від 1 до 10, а вектор - випадковими дійсними числами від 0 до 1, і знайдіть добуток матриці на вектор.
arr = np.random.randint(1, 11, size=(3, 4))
vec = np.random.rand(4, 1)

print(np.dot(arr, vec))

[[8.81626903]
 [8.84800069]
 [6.03248225]]


In [36]:
# Створіть матрицю розміром 2x3 та вектор розміром 3x1, заповніть матрицю випадковими дійсними числами від 0 до 1, а вектор - випадковими цілими числами в діапазоні від 1 до 10, і знайдіть добуток матриці на вектор.
arr = np.random.rand(2, 3)
vec = np.random.randint(1, 11, size=(3, 1))

print(np.dot(arr, vec))

[[3.97418954]
 [9.31257205]]


In [37]:
# Створіть дві матриці розміром 3x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 5 та знайдіть суму всіх елементів першої матриці.
arr1 = np.random.randint(1, 6, size=(3, 3))
arr2 = np.random.randint(1, 6, size=(3, 3))

print(np.sum(arr1))

22


In [38]:
# Створіть дві матриці розміром 4x4, заповніть їх випадковими дійсними числами в діапазоні від -2 до 2 та знайдіть добуток їх елементів.
arr1 = np.random.uniform(-2, 2, size=(4, 4))
arr2 = np.random.uniform(-2, 2, size=(4, 4))

print(np.prod(arr1 * arr2))

0.000916451025876211


In [39]:
# Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від -10 до 10 та знайдіть найменший елемент матриці.
arr = np.random.uniform(-10, 10, size=(3, 3))

print(np.min(arr))

-9.686202685467379


In [ ]:
# Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного стовпця матриці.
arr = np.random.rand(3, 3)
vec = np.sum(arr, axis=0)

print(vec)

# Висновок

В основному ми згадували основи роботи з Python та бібліотекою NumPy.

Ми створювали матриці та вектори, заповнювали їх випадковими числами, а потім виконували такі дії, як множення, додавання, віднімання, транспонування та знаходження оберненої матриці. Ми також обчислювали суми елементів, добутки та середні значення.